// Generated by https://quicktype.io

export interface PeopleTvShowResponse {
    cast: CastTv[];
    crew: CastTv[];
    id:   number;
}

export interface CastTv {
    adult:             boolean;
    backdrop_path:     null | string;
    genre_ids:         number[];
    id:                number;
    origin_country:    OriginCountry[];
    original_language: OriginalLanguage;
    original_name:     string;
    overview:          string;
    popularity:        number;
    poster_path:       null | string;
    first_air_date:    string;
    name:              string;
    vote_average:      number;
    vote_count:        number;
    character?:        string;
    credit_id:         string;
    episode_count?:    number;
    department?:       Department;
    job?:              string;
}

export enum Department {
    Creator = "Creator",
    Crew = "Crew",
    Production = "Production",
    Writing = "Writing",
}

export enum OriginCountry {
    CA = "CA",
    De = "DE",
    Jp = "JP",
    Us = "US",
}

export enum OriginalLanguage {
    De = "de",
    En = "en",
    Ja = "ja",
}
