// Generated by https://quicktype.io

export interface PeopleMovieResponse {
    cast: CastPelicula[];
    crew: CastPelicula[];
    id:   number;
}

export interface CastPelicula {
    adult:             boolean;
    backdrop_path:     null | string;
    genre_ids:         number[];
    id:                number;
    original_language: OriginalLanguage;
    original_title:    string;
    overview:          string;
    popularity:        number;
    poster_path:       null | string;
    release_date:      string;
    title:             string;
    video:             boolean;
    vote_average:      number;
    vote_count:        number;
    character?:        string;
    credit_id:         string;
    order?:            number;
    department?:       Department;
    job?:              string;
}

export enum Department {
    Camera = "Camera",
    Crew = "Crew",
    Directing = "Directing",
    Editing = "Editing",
    Production = "Production",
    Sound = "Sound",
    Writing = "Writing",
}

export enum OriginalLanguage {
    De = "de",
    En = "en",
    Es = "es",
    Fr = "fr",
    Ja = "ja",
}
